name: Create Release
on:
  workflow_dispatch:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  release:
    uses: dfuchss/actions/.github/workflows/github-release.yml@main
    
