name: Spotless & Formatter Checks

on:
  push:
    paths:
      - '**/src/**'
      - '**/pom.xml'
      - 'pom.xml'
  pull_request:
    types: [ opened, synchronize, reopened ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  verify:
    uses: dfuchss/actions/.github/workflows/maven.yml@main
    with:
      deploy: false
    secrets:
      CENTRAL_USER: ""
      CENTRAL_TOKEN: ""
      GPG_KEY: ""
